# -*- coding: utf-8 -*-
"""
/***************************************************************************
 selec_cidades
                                 A QGIS plugin
 De acordo com um municipio, seleciona cidades a uma certa distancia
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2019-10-17
        copyright            : (C) 2019 by Gabriele Camara
        email                : camaragabriele@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load selec_cidades class from file selec_cidades.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .selec_cidades import selec_cidades
    return selec_cidades(iface)
